var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var bookingSchema = new Schema({
        _id: String,
        property: String,
		user: String,
		agent: String,
		agentCommission: String,
		discount: String,
		discountPercentage: Number,
		checkin: Number,
		checkout: Number,
		status: Number,
		currency: String,
		paymentType: Number,
		paymentDate: Number,
		expires: Number,
		priceDay: Number,
		nights: Number,
		priceReservation: Number,
		priceSecurity: Number,
		cleanprice: Number,
		cleanfinalprice: Number,
		priceExtra: [],
		conditionsTenant: String,
		conditionsAgent: String,
		created: Number,
		updated: String,
		rate: Number,
		pricePaid: Number,
		emails: [],
		confirmation: Number,
		checked: Boolean,
		paymentconfirmed: Boolean,
		rentpayday: Number,
		lastpayment: Number,
		nextpayment: Number,
		comment: String,
		source: String,
		arrival: String,
		departure: String,
		electricPrice: Number,
		electricFrom: Number,
		waterFrom: Number,
		waterTo: Number,
		waterPrice: Number,
		electricTo: Number,
		discountAmount: String,
		longTermDay: Number,
		longTermAmount: Number
});
module.exports = mongoose.model('booking', bookingSchema, 'booking');